auto: true

markdown: kramdown
pygments: true
paginate: 8
permalink: /:title
highlighter: rouge

title: lvsong.club
url: http://www.lvsong.club
feed: /atom.xml
author_info: <a href="http://www.lvsong.club">lvsong</a>
